version: '2'
services:

  spring-boot-skeleton:
    image: spring-boot-skeleton:latest
    restart: always
    ports:
      - 8081:8081
    links:
      - mongo:app_db

  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
      - "8082:8082"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
       - spring-boot-skeleton
#NOTE: you can access the frontend in http://localhost:8080
#NOTE: you can access the backend in http://localhost:8080/backend/* eg http://localhost:8080/backend/test

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: spring-boot-skeleton
